services:
  soulmask:
    image: m3thod/soulmask-server-arm64:latest  # Use this name for the built image or pull it if not built
    container_name: Soulserver
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Dockerfile for building locally
    ports:
      - "27050:27050/udp"
      - "27015:27015/udp"
      - "18888:18888/tcp"
    env_file:
      - default.env
    volumes:
      - soulmask-persistent-data:/home/steam/soulmask
    stop_grace_period: 90s
    healthcheck:
      test: ["CMD-SHELL", "grep -q \"REGISTER SERVER ERROR\" /home/steam/soulmask/WS/Saved/Logs/WS.log || exit 1"]
      interval: 1m  # Check every 1 minute
      timeout: 10s  # Wait for 10 seconds before considering the health check failed
      retries: 3  # Allow 3 retries before considering the container unhealthy
      start_period: 30s  # Initial delay before starting health checks

volumes:
  soulmask-persistent-data:
